#!/usr/bin/bash
set -euo pipefail

input_file="${1:-web-root.html}"
output_file="${2:-web-root-html.h}"

if [ ! -f "$input_file" ]; then
  echo "Input file not found: $input_file" >&2
  exit 1
fi

{
  echo "#pragma once"
  echo
  echo "// Auto-generated from $input_file. Do not edit this file manually."
  echo "const char WEB_ROOT_HTML[] PROGMEM ="

  while IFS= read -r line || [ -n "$line" ]; do
    line=${line//\\/\\\\}
    line=${line//\"/\\\"}
    printf '  "%s\\n"\n' "$line"
  done < "$input_file"

  echo ";"
} > "$output_file"

echo "Generated $output_file from $input_file"
